function [Time, EKGProFlex1A, HRBVPProFlex1B, SCProFlex1C, RespProFlex1D] = importfile_procomp(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [TIME, EKGPROFLEX1A, HRBVPPROFLEX1B, SCPROFLEX1C, RESPPROFLEX1D] =
%  IMPORTFILE(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as column vectors.
%
%  [TIME, EKGPROFLEX1A, HRBVPPROFLEX1B, SCPROFLEX1C, RESPPROFLEX1D] =
%  IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  [Time, EKGProFlex1A, HRBVPProFlex1B, SCProFlex1C, RespProFlex1D] = importfile("C:\Users\megaa\OneDrive\Desktop\UNIVERSITA\POLIMI\TESI\ANALISI MATLAB\D358FL.txt", [8, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 31-Mar-2022 10:55:34

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [8, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Time", "EKGProFlex1A", "HRBVPProFlex1B", "SCProFlex1C", "RespProFlex1D"];
opts.VariableTypes = ["double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Time", "EKGProFlex1A", "HRBVPProFlex1B", "SCProFlex1C", "RespProFlex1D"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["Time", "EKGProFlex1A", "HRBVPProFlex1B", "SCProFlex1C", "RespProFlex1D"], "DecimalSeparator", ",");
opts = setvaropts(opts, ["Time", "EKGProFlex1A", "HRBVPProFlex1B", "SCProFlex1C", "RespProFlex1D"], "ThousandsSeparator", ".");

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
Time = tbl.Time;
EKGProFlex1A = tbl.EKGProFlex1A;
HRBVPProFlex1B = tbl.HRBVPProFlex1B;
SCProFlex1C = tbl.SCProFlex1C;
RespProFlex1D = tbl.RespProFlex1D;
end